### ISSUE TITLE
1909 only???

### ISSUE THREAD

**Issue by Anonymoushacker4926** [Lufzys/SimpleHWIDSpoofer#2]
I tried it & compiled it successfully, but it doesn't work. It just says run as administrator even though I did. I run other spoofers which also changed my windows version to 19043.1083. so what do I need to do?

**Comment by Lufzys** [comment]
I don't think this program can change the hwid information as you want. if you are looking for a real hwid spoofer you can check this resource https://github.com/btbd/hwid. 
Sorry for the late reply, I just realized
